name: Build
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        arduino-platform: ["esp32:esp32"]

        include:
          - arduino-platform: "esp32:esp32"
            fqbn: "esp32:esp32:esp32"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@master

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip pyserial

      - name: Install Platform
        run: |
          arduino-cli core update-index --verbose
          arduino-cli core install ${{ matrix.arduino-platform }} --verbose

      - name: Install Libraries
        run: |
          arduino-cli lib update-index --verbose
          arduino-cli lib install NTPClient FastLED ArduinoJson --verbose

      - name: Compile sketch
        run: |
          arduino-cli compile --fqbn ${{ matrix.fqbn }} "test" --verbose
