name: Lint Code Base

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  linting:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v2.0.0
        # See https://github.com/github/super-linter/ for configuration
        # documentation
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GO: false
          VALIDATE_XML: false
          VALIDATE_PERL: false
          VALIDATE_RUBY: false
          VALIDATE_COFFEE: false
          VALIDATE_ANSIBLE: false
          VALIDATE_DOCKER: false
          VALIDATE_TERRAFORM: false
          VALIDATE_PYTHON: false
          VALIDATE_JAVASCRIPT_ES: false
